# Generated by Django 3.1.6 on 2021-02-25 06:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0010_auto_20210225_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectOfInterest',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('d0b2c3bb-26da-4e48-a72e-891e10fd634a'), unique=True)),
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('subject_of_interest', models.CharField(max_length=100)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('aa0a4255-515d-4e36-b852-90355e107fac'), primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('website', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, default=None, max_length=12, null=True)),
                ('mobile', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('address', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('date_of_birth', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('00b59c35-87d9-48f6-88e4-8c92ec034768'), primary_key=True, serialize=False, unique=True)),
                ('designation', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('department', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('institute', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.teacher')),
            ],
        ),
    ]
