# Generated by Django 3.1.6 on 2021-03-11 05:30

import Dashboard.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0002_auto_20210311_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilePicFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bytes', models.TextField()),
                ('filename', models.CharField(max_length=255)),
                ('mimetype', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Workshops',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('280e3769-e778-4556-a695-0f7c189e130c'), unique=True)),
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('organization', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=5)),
                ('date_form', models.CharField(max_length=10)),
                ('date_to', models.CharField(max_length=10)),
                ('day', models.IntegerField()),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='TeachingExperience',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('3ab102ab-a200-4633-93f9-fba39a0dfb46'), unique=True)),
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('date_of_join', models.CharField(max_length=10)),
                ('date_of_leave', models.CharField(max_length=10)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectOfInterest',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('269cce37-fbe5-4de8-9978-2fd0a99ae822'), unique=True)),
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('subject_of_interest', models.CharField(max_length=100)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='ShortTermsTrainingProgram',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('5924aba3-02c1-43d4-a266-afb748539b94'), unique=True)),
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('organization', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=5)),
                ('date_form', models.CharField(max_length=10)),
                ('date_to', models.CharField(max_length=10)),
                ('day', models.IntegerField()),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='PublicationsPaper',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('8f38d414-2880-4ed8-88ae-a3f5730aff38'), unique=True)),
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('publication', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=5)),
                ('url', models.CharField(max_length=300)),
                ('level', models.CharField(max_length=15)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='PublicationsJournal',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('82c5feb1-9a88-4d92-9467-916b06c3c43d'), unique=True)),
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('publication', models.CharField(max_length=100)),
                ('page', models.CharField(max_length=10)),
                ('year', models.CharField(max_length=5)),
                ('url', models.CharField(max_length=300)),
                ('level', models.CharField(max_length=15)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='PublicationsBook',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('49956590-73d6-4643-8f41-19613d88f357'), unique=True)),
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('publication', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=100)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectGuided',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('4da4e4ef-094c-4973-b3ae-2e0992888866'), unique=True)),
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=5)),
                ('level', models.CharField(max_length=3)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('bbc2e8ca-7746-4106-b2fb-f2541e68f0d2'), unique=True)),
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('society', models.CharField(max_length=100)),
                ('ist_no', models.CharField(max_length=100)),
                ('date_of_membership', models.CharField(max_length=10)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='OtherInstituteInteractions',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('f25f20c4-993f-4c29-a199-08f1a9947705'), unique=True)),
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('organization', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=5)),
                ('invitee', models.CharField(max_length=20)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='IndustrialExperience',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('6fc7b03a-891d-4046-a1e2-1dd57bd8745f'), unique=True)),
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('date_of_join', models.CharField(max_length=10)),
                ('date_of_leave', models.CharField(max_length=10)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='FacultyDevelopment',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('541ff417-6a50-4a2b-803c-cf4421140cb3'), unique=True)),
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('date_of_approval', models.CharField(max_length=10)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='ExtraCurricularActivities',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('cc4d2675-c331-42da-94b8-57f8255f69e5'), unique=True)),
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=5)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('045b17ef-e97e-4b14-8222-6ccbecfb4ff9'), primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('website', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, default=None, max_length=12, null=True)),
                ('mobile', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('address', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('date_of_birth', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('profile_file', models.FileField(blank=True, default=None, null=True, upload_to=Dashboard.models.profile_pic_file_name)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('3825f512-28c4-47a7-984a-f9f2a8087074'), primary_key=True, serialize=False, unique=True)),
                ('designation', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('department', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('institute', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Consultancy',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('07f84853-fa8f-4d9d-ae0c-211fcd025b71'), unique=True)),
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('organization', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=5)),
                ('work_done', models.CharField(max_length=300)),
                ('cost', models.CharField(max_length=20)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='AwardReceived',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('040a4e5d-4e4e-40c3-bbd7-6c56c8121d20'), unique=True)),
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('organization', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=5)),
                ('title', models.CharField(max_length=100)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='AdministrativeExperience',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('688e1613-86c5-4ddb-9800-19cf7fb77a50'), unique=True)),
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('date_of_join', models.CharField(max_length=10)),
                ('date_of_leave', models.CharField(max_length=10)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Academics',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('b9d3bdb0-f957-406e-9e56-51324f4f7be8'), unique=True)),
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('degree', models.CharField(max_length=100)),
                ('specialisation', models.CharField(max_length=100)),
                ('university', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=10)),
                ('remarks', models.CharField(max_length=100)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.teacher')),
            ],
        ),
    ]
