# Generated by Django 3.1.6 on 2021-02-24 17:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0009_auto_20210224_2321'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectOfInterest',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('9961af09-056b-4335-96a8-b96db750ab97'), primary_key=True, serialize=False, unique=True)),
                ('subject_of_interest', models.CharField(max_length=100)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('7b001fab-1e3e-45ba-8cc5-3034499c3ba0'), primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('website', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, default=None, max_length=12, null=True)),
                ('mobile', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('address', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('date_of_birth', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('cdf9a671-c6cd-4bfd-a56b-c44ee9be00a6'), primary_key=True, serialize=False, unique=True)),
                ('designation', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('department', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('institute', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.teacher')),
            ],
        ),
    ]
