# Generated by Django 3.1.6 on 2021-02-25 08:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0011_auto_20210225_1356'),
        ('Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designation',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8d8babc9-eece-47d9-a967-f59b2d41d1d3'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6defe6d4-da4c-443e-ac6e-58d21a787a4c'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='subjectofinterest',
            name='id',
            field=models.UUIDField(default=uuid.UUID('66b9193e-8f57-4ce3-99de-3bb1519c6d9d'), unique=True),
        ),
        migrations.CreateModel(
            name='TeachingExperience',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('01510402-6461-4ff3-9528-140bfa99cb13'), unique=True)),
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('date_of_join', models.CharField(max_length=10)),
                ('date_of_leave', models.CharField(max_length=10)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('ceaba603-ef1b-462c-96de-ea854af51345'), unique=True)),
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('society', models.CharField(max_length=100)),
                ('ist_no', models.CharField(max_length=100)),
                ('date_of_membership', models.CharField(max_length=10)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='IndustrialExperience',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('a04061f3-a023-49f1-b04c-52b0a984e899'), unique=True)),
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('date_of_join', models.CharField(max_length=10)),
                ('date_of_leave', models.CharField(max_length=10)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='FacultyDevelopment',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('1c889762-9ecc-43f8-bc28-122e57682336'), unique=True)),
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('date_of_approval', models.CharField(max_length=10)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='AdministrativeExperience',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('b0e6a0ba-f7cf-493f-8f73-4d5bcc35398c'), unique=True)),
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('date_of_join', models.CharField(max_length=10)),
                ('date_of_leave', models.CharField(max_length=10)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Academics',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('663f4027-e30c-40e4-b77f-23a4107c33bb'), unique=True)),
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('degree', models.CharField(max_length=100)),
                ('specialisation', models.CharField(max_length=100)),
                ('university', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=10)),
                ('remarks', models.CharField(max_length=100)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.teacher')),
            ],
        ),
    ]
