# Generated by Django 3.1.6 on 2021-03-11 05:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeStudentData',
            fields=[
                ('prn', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('mother_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CollegeTeacherData',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('aca3227b-76a6-4f37-b1a9-89b1d6542649'), primary_key=True, serialize=False, unique=True)),
                ('email_verification', models.BooleanField(default=False)),
                ('password_state', models.BooleanField(default=True)),
                ('college_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.collegeteacherdata')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('95e6df68-edf6-492e-ac5b-541badfcfa46'), primary_key=True, serialize=False, unique=True)),
                ('email_verification', models.BooleanField(default=False)),
                ('password_state', models.BooleanField(default=True)),
                ('college_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.collegestudentdata')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
