# Generated by Django 3.1.6 on 2021-03-11 05:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8ad5d7cd-0478-455e-9f7e-aa8089723445'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cacf64e7-c12c-4a2b-81d5-737a94f73e4f'), primary_key=True, serialize=False, unique=True),
        ),
    ]
