# Generated by Django 3.1.6 on 2021-02-17 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('08aac822-c9f2-464b-8450-caca3c89832c'), primary_key=True, serialize=False, unique=True)),
                ('email_verification', models.BooleanField(default=False)),
                ('college_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.collegestudentdata')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
