# Generated by Django 3.1.6 on 2021-02-21 16:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password_state',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6180deaa-643b-4ecd-bffa-21718cc55bfd'), primary_key=True, serialize=False, unique=True),
        ),
    ]
