# Generated by Django 3.1.6 on 2021-02-22 04:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_auto_20210221_2150'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeTeacherData',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=70)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f95c24cc-47c4-43b6-b36b-3a54e35f6f0a'), primary_key=True, serialize=False, unique=True),
        ),
    ]
