# Generated by Django 3.1.6 on 2021-02-22 05:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('User', '0004_auto_20210222_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0733910a-6be2-4f9f-85af-de398476e817'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('f1a0701f-4cc9-4277-b554-4a116e726b69'), primary_key=True, serialize=False, unique=True)),
                ('email_verification', models.BooleanField(default=False)),
                ('password_state', models.BooleanField(default=True)),
                ('college_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.collegeteacherdata')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
