# Generated by Django 3.1.6 on 2021-02-24 06:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_auto_20210222_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.UUIDField(default=uuid.UUID('477bbde4-1c05-4d48-a5a2-0a7af64bbf73'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0bcf8cec-703b-49cd-9edd-db4bd7cc5bde'), primary_key=True, serialize=False, unique=True),
        ),
    ]
