# Generated by Django 3.1.6 on 2021-02-24 11:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_auto_20210224_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.UUIDField(default=uuid.UUID('23203e64-169e-4168-b838-db8619e96dd4'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ede6b7d4-f428-44f3-8787-297411c87fcd'), primary_key=True, serialize=False, unique=True),
        ),
    ]
