# Generated by Django 3.1.6 on 2021-02-24 16:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_auto_20210224_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.UUIDField(default=uuid.UUID('32465d0c-bbbf-47ec-a802-f50ff32b02fa'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='id',
            field=models.UUIDField(default=uuid.UUID('db637698-766d-4dd8-9555-02b521f74436'), primary_key=True, serialize=False, unique=True),
        ),
    ]
