# Generated by Django 3.1.6 on 2021-02-24 17:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_auto_20210224_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d5793726-a533-40aa-9d86-7e56490ed404'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='id',
            field=models.UUIDField(default=uuid.UUID('966da266-afd9-4349-95b5-4c6bc9845589'), primary_key=True, serialize=False, unique=True),
        ),
    ]
