# Generated by Django 3.1.6 on 2021-02-25 06:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0009_auto_20210224_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.UUIDField(default=uuid.UUID('20f17256-3f7c-423c-997d-6f62b5b97cf4'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7ea0ab34-46d6-4e9b-b50f-c7aa7a09aaef'), primary_key=True, serialize=False, unique=True),
        ),
    ]
