# Generated by Django 3.1.6 on 2021-02-25 08:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0010_auto_20210225_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.UUIDField(default=uuid.UUID('80cd43fe-0f9d-485a-897f-ad0be6f97f7f'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='id',
            field=models.UUIDField(default=uuid.UUID('00b4e0a8-c6a5-4547-9f82-c2934d2b57bb'), primary_key=True, serialize=False, unique=True),
        ),
    ]
