# Generated by Django 3.1.6 on 2021-02-27 04:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0011_auto_20210225_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.UUIDField(default=uuid.UUID('eee9c69b-b68d-40f6-b7e8-29009b5190eb'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f59f2690-684d-4c5b-94cb-8628c58783b0'), primary_key=True, serialize=False, unique=True),
        ),
    ]
